name: Build using Bilt
on: ['push']
jobs:
  generateBuildInformation:
    name: "Generate 'Needs Build' information'"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Install Bilt
      run: npm install -g @bilt/github-actions-workflow
    outputs:
  build-template:
    name: "$packageNames"
    runs-on: ubuntu-latest
    needs:
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Enable Git Push
      run: |
        git config --global user.email "bilt-ci@example.com"
        git config --global user.name "Bilt CI"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15
        registry-url: 'https://registry.npmjs.org'
    - name: Install Bilt
      run: npm install -g @bilt/cli
    - name: "Build"
      run: bilt $packageNames -m 'CI Build'
